// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MVP.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AwardCategory
    {
        /// <summary>
        /// Initializes a new instance of the AwardCategory class.
        /// </summary>
        public AwardCategory() { }

        /// <summary>
        /// Initializes a new instance of the AwardCategory class.
        /// </summary>
        public AwardCategory(Guid? awardCategoryId = default(Guid?), string name = default(string))
        {
            AwardCategoryId = awardCategoryId;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardCategoryId")]
        public Guid? AwardCategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
