// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MVP.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AwardCycle
    {
        /// <summary>
        /// Initializes a new instance of the AwardCycle class.
        /// </summary>
        public AwardCycle() { }

        /// <summary>
        /// Initializes a new instance of the AwardCycle class.
        /// </summary>
        public AwardCycle(Guid? awardCycleId = default(Guid?), DateTime? awardPeriodEndDate = default(DateTime?), DateTime? awardPeriodStartDate = default(DateTime?), DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string name = default(string))
        {
            AwardCycleId = awardCycleId;
            AwardPeriodEndDate = awardPeriodEndDate;
            AwardPeriodStartDate = awardPeriodStartDate;
            StartDate = startDate;
            EndDate = endDate;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardCycleId")]
        public Guid? AwardCycleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardPeriodEndDate")]
        public DateTime? AwardPeriodEndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardPeriodStartDate")]
        public DateTime? AwardPeriodStartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndDate")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
