// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MVP.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContributionsModel
    {
        /// <summary>
        /// Initializes a new instance of the ContributionsModel class.
        /// </summary>
        public ContributionsModel() { }

        /// <summary>
        /// Initializes a new instance of the ContributionsModel class.
        /// </summary>
        public ContributionsModel(int? contributionId = default(int?), string contributionTypeName = default(string), ActivityTypeViewModel activityType = default(ActivityTypeViewModel), ActivityTechnologyViewModel applicableTechnology = default(ActivityTechnologyViewModel), DateTime? dateOfActivity = default(DateTime?), string titleOfActivity = default(string), string referenceUrl = default(string), VisibilityViewModel activityVisibility = default(VisibilityViewModel), int? annualQuantity = default(int?), int? secondAnnualQuantity = default(int?), int? annualReach = default(int?), string description = default(string))
        {
            ContributionId = contributionId;
            ContributionTypeName = contributionTypeName;
            ActivityType = activityType;
            ApplicableTechnology = applicableTechnology;
            DateOfActivity = dateOfActivity;
            TitleOfActivity = titleOfActivity;
            ReferenceUrl = referenceUrl;
            ActivityVisibility = activityVisibility;
            AnnualQuantity = annualQuantity;
            SecondAnnualQuantity = secondAnnualQuantity;
            AnnualReach = annualReach;
            Description = description;
        }

        /// <summary>
        /// Gets or sets the Contribution table id.
        /// </summary>
        [JsonProperty(PropertyName = "ContributionId")]
        public int? ContributionId { get; set; }

        /// <summary>
        /// Name of the contribution type
        /// </summary>
        [JsonProperty(PropertyName = "ContributionTypeName")]
        public string ContributionTypeName { get; set; }

        /// <summary>
        /// Gets or sets the contribution type.
        /// </summary>
        [JsonProperty(PropertyName = "ActivityType")]
        public ActivityTypeViewModel ActivityType { get; set; }

        /// <summary>
        /// Gets or sets the contribution technology.
        /// </summary>
        [JsonProperty(PropertyName = "ApplicableTechnology")]
        public ActivityTechnologyViewModel ApplicableTechnology { get; set; }

        /// <summary>
        /// Gets or sets the start date.
        /// </summary>
        [JsonProperty(PropertyName = "DateOfActivity")]
        public DateTime? DateOfActivity { get; set; }

        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        [JsonProperty(PropertyName = "TitleOfActivity")]
        public string TitleOfActivity { get; set; }

        /// <summary>
        /// Gets or sets the url.
        /// </summary>
        [JsonProperty(PropertyName = "ReferenceUrl")]
        public string ReferenceUrl { get; set; }

        /// <summary>
        /// Gets or sets the visibility.
        /// </summary>
        [JsonProperty(PropertyName = "ActivityVisibility")]
        public VisibilityViewModel ActivityVisibility { get; set; }

        /// <summary>
        /// Gets or sets the annual quantity.
        /// </summary>
        [JsonProperty(PropertyName = "AnnualQuantity")]
        public int? AnnualQuantity { get; set; }

        /// <summary>
        /// Gets or sets the second annual quantity.
        /// </summary>
        [JsonProperty(PropertyName = "SecondAnnualQuantity")]
        public int? SecondAnnualQuantity { get; set; }

        /// <summary>
        /// Gets or sets the reach score.
        /// </summary>
        [JsonProperty(PropertyName = "AnnualReach")]
        public int? AnnualReach { get; set; }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.ApplicableTechnology != null)
            {
                this.ApplicableTechnology.Validate();
            }
        }
    }
}
