// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MVP.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContributionTechnology
    {
        /// <summary>
        /// Initializes a new instance of the ContributionTechnology class.
        /// </summary>
        public ContributionTechnology() { }

        /// <summary>
        /// Initializes a new instance of the ContributionTechnology class.
        /// </summary>
        public ContributionTechnology(Guid? contributionTechnologyId = default(Guid?), string name = default(string), Program program = default(Program), AwardCategory awardCategory = default(AwardCategory))
        {
            ContributionTechnologyId = contributionTechnologyId;
            Name = name;
            Program = program;
            AwardCategory = awardCategory;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionTechnologyId")]
        public Guid? ContributionTechnologyId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Program")]
        public Program Program { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardCategory")]
        public AwardCategory AwardCategory { get; set; }

    }
}
