// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MVP.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ContributionType
    {
        /// <summary>
        /// Initializes a new instance of the ContributionType class.
        /// </summary>
        public ContributionType() { }

        /// <summary>
        /// Initializes a new instance of the ContributionType class.
        /// </summary>
        public ContributionType(Guid? contributionTypeId = default(Guid?), string typeName = default(string), ContributionTypeContributionCategory contributionCategory = default(ContributionTypeContributionCategory))
        {
            ContributionTypeId = contributionTypeId;
            TypeName = typeName;
            ContributionCategory = contributionCategory;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionTypeId")]
        public Guid? ContributionTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TypeName")]
        public string TypeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionCategory")]
        public ContributionTypeContributionCategory ContributionCategory { get; set; }

    }
}
