// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MVP.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Contribution
    {
        /// <summary>
        /// Initializes a new instance of the Contribution class.
        /// </summary>
        public Contribution() { }

        /// <summary>
        /// Initializes a new instance of the Contribution class.
        /// </summary>
        public Contribution(int? privateSiteId = default(int?), string contributionId = default(string), Guid? contributionsId = default(Guid?), Guid? mvpGuid = default(Guid?), string contributor = default(string), int? annualQuantity = default(int?), int? secondAnnualQuantity = default(int?), DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), SocialNetwork onlinePropertyName = default(SocialNetwork), string url = default(string), string title = default(string), ContributionTechnology contributionTechnology = default(ContributionTechnology), ContributionType contributionType = default(ContributionType), string description = default(string), int? annualReach = default(int?), AwardCycle awardPeriod = default(AwardCycle), Language forumLanguage = default(Language), SharingPreference visibility = default(SharingPreference), bool? belongToLatestAwardCycle = default(bool?), OnlineIdentity onlineIdentity = default(OnlineIdentity), int? dataSource = default(int?), Technology applicableTechnology = default(Technology), bool? submitted = default(bool?))
        {
            PrivateSiteId = privateSiteId;
            ContributionId = contributionId;
            ContributionsId = contributionsId;
            MvpGuid = mvpGuid;
            Contributor = contributor;
            AnnualQuantity = annualQuantity;
            SecondAnnualQuantity = secondAnnualQuantity;
            StartDate = startDate;
            EndDate = endDate;
            OnlinePropertyName = onlinePropertyName;
            Url = url;
            Title = title;
            ContributionTechnology = contributionTechnology;
            ContributionType = contributionType;
            Description = description;
            AnnualReach = annualReach;
            AwardPeriod = awardPeriod;
            ForumLanguage = forumLanguage;
            Visibility = visibility;
            BelongToLatestAwardCycle = belongToLatestAwardCycle;
            OnlineIdentity = onlineIdentity;
            DataSource = dataSource;
            ApplicableTechnology = applicableTechnology;
            Submitted = submitted;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrivateSiteId")]
        public int? PrivateSiteId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionId")]
        public string ContributionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionsId")]
        public Guid? ContributionsId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MvpGuid")]
        public Guid? MvpGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Contributor")]
        public string Contributor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AnnualQuantity")]
        public int? AnnualQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SecondAnnualQuantity")]
        public int? SecondAnnualQuantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndDate")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OnlinePropertyName")]
        public SocialNetwork OnlinePropertyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionTechnology")]
        public ContributionTechnology ContributionTechnology { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionType")]
        public ContributionType ContributionType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AnnualReach")]
        public int? AnnualReach { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardPeriod")]
        public AwardCycle AwardPeriod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ForumLanguage")]
        public Language ForumLanguage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Visibility")]
        public SharingPreference Visibility { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BelongToLatestAwardCycle")]
        public bool? BelongToLatestAwardCycle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OnlineIdentity")]
        public OnlineIdentity OnlineIdentity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DataSource")]
        public int? DataSource { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApplicableTechnology")]
        public Technology ApplicableTechnology { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Submitted")]
        public bool? Submitted { get; set; }

    }
}
