// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MVP.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Language
    {
        /// <summary>
        /// Initializes a new instance of the Language class.
        /// </summary>
        public Language() { }

        /// <summary>
        /// Initializes a new instance of the Language class.
        /// </summary>
        public Language(Guid? languageId = default(Guid?), string name = default(string))
        {
            LanguageId = languageId;
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LanguageId")]
        public Guid? LanguageId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
